version: '3'
services:
  web:
    build: ./client
    ports:
      - "3000:3000"
    depends_on: 
      - server
  server:
    build: ./server
    ports:
      - "4000:4000"
    # volumes: 
    #   - ./server:/
  # mongodb:
  #   image: "mongo"
  #   ports:
  #    - "27017:27017"