version: '3'

services:
  vrmsapp:
    build: .
    ports:
      - 4000:4000
    env_file:
      - .env

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=testdb
    volumes:
      - ./data/db:/data/db