name: Build VMRS App
on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  CUSTOM_REQUEST_HEADER: ${{ secrets.CUSTOM_REQUEST_HEADER }}
  SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_TOKEN }}
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  SLACK_TEAM_ID: ${{ secrets.SLACK_TEAM_ID }}
  SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
  SLACK_CLIENT_ID: ${{ secrets.SLACK_CLIENT_ID }}
  SLACK_CLIENT_SECRET: ${{ secrets.SLACK_CLIENT_SECRET }}
  SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
  BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
  REACT_APP_PROXY: ${{ secrets.REACT_APP_PROXY }}
  GMAIL_CLIENT_ID: ${{ secrets.GMAIL_CLIENT_ID }}
  GMAIL_SECRET_ID: ${{ secrets.GMAIL_SECRET_ID }}
  GMAIL_REFRESH_TOKEN: ${{ secrets.GMAIL_REFRESH_TOKEN }}
  GMAIL_EMAIL: ${{ secrets.GMAIL_EMAIL }}

jobs:
  # Label of the container job
  run-unit-tests:
    # You must use a Linux environment when using service containers or container jobs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the backend container
        run: docker-compose -f docker-compose-ci.yaml build backend
      - name: Run backend test suite
        run: docker-compose -f docker-compose-ci.yaml run --rm backend yarn run test
        env:
          SLACK_BOT_TOKEN: Mona
          SLACK_SIGNING_SECRET: The
      - name: Build the frontend container
        run: docker-compose build client
      - name: Run frontend test suite
        run: docker-compose run --rm client yarn run test
