name: Build VMRS App
on:
  pull_request:
    branches:
      - development
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the backend container
        run: docker-compose -f docker-compose-ci.yaml build backend
      - name: Run backend test suite
        run: docker-compose -f docker-compose-ci.yaml run --rm backend yarn run test --testPathIgnorePatterns=routers
      - name: Build the frontend container
        run: docker-compose build client
      - name: Run frontend test suite
        run: docker-compose run --rm client yarn run test

  push-docker-container:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
      runs-on: ubuntu-latest
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1
        - name: Set up Docker Buildx
          target: api-production
            platforms: linux/amd64
            push: true
            tags: |
              vrmsdeploy/vrms:backend
        - name: Build and push client
          uses: docker/build-push-action@v2
          with:
            context: ./client
            file: ./client/Dockerfile.client
            platforms: linux/amd64
            target: client-production
            stdin_open: true
            push: true
            tags: |
              vrmsdeploy/vrms:client
        - name: Build and push nginx
          uses: docker/build-push-action@v2
          with:
            context: ./nginx
            file: ./nginx/Dockerfile.nginx
            platforms: linux/amd64
            push: true
            tags: |
              vrmsdeploy/vrms:nginx
        - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}
      uses: docker/setup-buildx-action@v1
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and push backend
          uses: docker/build-push-action@v2
          with:
            context: ./backend
            file: ./backend/Dockerfile.api
          
