name: Build VMRS App
on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  # Label of the container job
  run-unit-tests:
    # You must use a Linux environment when using service containers or container jobs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the backend container
        run: docker-compose -f docker-compose-ci.yaml build backend
      - name: Run backend test suite
        run: docker-compose -f docker-compose-ci.yaml run --rm backend yarn run test
      - name: Build the frontend container
        run: docker-compose build client
      - name: Run frontend test suite
        run: docker-compose run --rm client yarn run test
